### PR TITLE
Loading the models

### PR DESCRIPTION
**Pull request by MohammedAlkutrani**
Loading the models and save them in `$loader` property 
then you can chain to `pick` method to pick from them or get them as a collection by `toCollection` method in case another developer wants to use them as a collection.

### CODE REVIEW

**Comment by christophrumpel** [comment]
Wow thanks, you are on fire 🔥:-)

It would make work perfect sense for laravel factories reloaded, but I don't like it for this package here. It should just let the user pick a file. When the user sees more public methods available from the trait, I would find it distracting. It feels like hacking the code to make it work for this one use-case.

Currently, I see two possibilities:

1. we add a callback as second param to the `askTo PickModel` or class method where we can defined what files should be ignored. With the callback the user can decide the params for when files should be ignored.

2.  we leave this package as it is and check `after` the use picked the model if the factory already exists, and when it does we when show an error. (This would be the easiest solution)

What do you think? 

PS: Again thanks for your effort.

**Comment by MohammedAlkutrani** [comment]
Hey, sorry for being late. 

it seems like I didn't explain this PR well.
but before begin the explanation, I made little refactoring, I changed `loadModels`,`toCollection` and `pick` methods to `protected`, so nothing is `public` anymore.

The usage would be the same for the developers who already using this package, the `askToPickModels` method uses the `loadModels` method and directly chaining to `pick` to do the same behavior.

the main purpose of this PR is that you can manipulate what did you load.
so you can do that via `loadModels` method to load models and chain that to `toCollection` method to get a collection you can manipulate and call `pick` to pick as well.

It’s your choice to merge or close. 
I’ll thankful for your kindness anyway 🙂

thank you @christophrumpel

**Comment by MohammedAlkutrani** [comment]
It’s your choice to merge or close. 
I’ll thankful for your kindness anyway 🙂

**Comment by christophrumpel** [comment]
Hey,

I'm also late sorry :-) Thanks for the further info, but I'm still not fond of it. Even the methods are protected now, the user using it inside the Laravel Command will see all those methods and I find this distracting.

I will think of a different approach. Still thanks for your effort here Mohammed.

**Comment by christophrumpel** [comment]
Hey, I just pushed a new version for the file picker where you can "filter" the loaded files https://github.com/christophrumpel/laravel-command-file-picker#filter-loaded-files

Now in this package we can make use of this and add a method to the command to check if there is already a factory for the models. Do you want to implement that here?

If you can do it today or tomorrow that would be cool. If not I will do it myself. I just need it on Friday :-)

**Pull request closed without merging**
